name: got-train-dt-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas==1.5.3
      - scikit-learn==1.3.0
      - joblib==1.3.0
      - azureml-mlflow==1.53.0
      - mlflow==2.8.0